### ISSUE TITLE
Rate provider/workshop

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Backend#112]
Implement an ability to rate a provider or workshop using an integer number from 1 to 5.
Application should:
* allow each user to rate each provider/workshop only once.
* internally track who (which user) rated the provider/workshop and what rating value he/she used.
* each provider/workshop should have an average rating (float) displayed

Optional:
* user should be able to modify his/hers rating of a certain provider/workshop

**Comment by v-ivanchuk** [comment]
Dear @DmyMi @dmitrykiev @,

Please check my proposed scenario:
1. Need to add two new tables: ProviderRating and WorkshopRating. 
These tables consist of such fields as 
- UserId
- ProviderId/WorkshopId
- Rating (from 1-5)
- Id
- (maybe others)
The table can have only one record with the same UserId and ProviderId/WorkshopId. This resolves the first sub-point of the task. At the same time, this resolves an optional sub-point. Because the rating could be updated.
2. Second sub-point of the task could be developed later. But it will be consist of the grouped data from the previous table(-s).
3. Average rating of each provider/workshop should be track dynamically based on the grouped data from tables (first point). But I can't tell currently how to implement this point in code. Need to investigate deeper.
Please let me know your thoughts in order to continue with this task.
Thank you in advance.

**Comment by v-ivanchuk** [comment]
UPD:
Agreed on the meeting to add only one general column.
For this also need to add EntityType field that consists of the next enum (currently ProviderRating and WorkshopRating)
And set up Primary key as (UserId and ProviderId/WorkshopId)
